services:
  app:
    build: .
    ports:
      - '8091:8091'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.railway.internal:5432/railway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=GoTXZTOyqUmOLzADITuJOlWHhkJgrUHb
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=GoTXZTOyqUmOLzADITuJOlWHhkJgrUHb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: